version: '3.8'

volumes:
    app:
    redis:
    storage:
    mysql:

networks:
    laravel:

services:
    nginx:
      image: nginx:alpine
      ports:
        - "10000:8001"
      volumes:
        - ./src:/var/www/app
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on: 
        - php
        - mysql
      networks: 
        - laravel

    php:
      build:
          context: .
          dockerfile: Dockerfile
      user: "1000:1000"
      tty: true
      working_dir: /var/www/app
      volumes: 
        - ./src:/var/www/app
        - /var/www/app/vendor
      networks: 
        - laravel

    mysql:
      image: mysql:latest
      restart: unless-stopped
      tty: true
      volumes: 
          - mysql:/var/lib/mysql
      environment: 
          MYSQL_DATABASE: laravel
          MYSQL_USER: user
          MYSQL_PASSWORD: user
          MYSQL_ROOT_PASSWORD: root
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
      networks: 
          - laravel

    phpmyadmin:
      image: phpmyadmin:latest
      environment:
        - PMA_HOST=mysql
        - PMA_ABSOLUTE_URI=http://localhost:10000/phpmyadmin/
      networks: 
          - laravel
    
    node:
      image: node:lts
      volumes:
        - ./src:/app  

    s3:
      image: bitnami/minio:latest
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - storage:/data

    soketi:
      image: quay.io/soketi/soketi:latest-16-alpine
      ports:
        - "6001:6001"
        - "9601:9601"

    redis:
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - redis:/data

    cloudfront:
      image: halverneus/static-file-server

    composer:
      image: composer:latest
      volumes:
        - ./src:/app  


